server:
  port: 7073
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lanchonete?&serverTimezone=UTC
    username: root
    password: admin
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true